### ISSUE TITLE
Assertion Error: Trying to convert grid2op to GymEnv using grid2op.compat

### ISSUE THREAD

**Issue by vishrutmishra** [rte-france/Grid2Op#185]
## Environment
 - Grid2op version: `1.5.0`
 - System: `windows 10`
 - Additional system information

## Bug description

Cannot convert grid2op to the gym environment using the code snippet given on https://grid2op.readthedocs.io/en/latest/gym.html

## How to reproduce

I tried to convert grip2op into a gym environment. But it gave us an assertion error.

### Command line

```bash
# no command line used.
```

### Code snippet

```python
import grid2op
from grid2op.gym_compat import GymEnv
env_name = "l2rpn_case14_sandbox"
env = grid2op.make(env_name)
gym_env = GymEnv(env)
```

## Current output

```
Traceback (most recent call last):
  File "D:\projects\cse574\demo\grid2op-demo.py", line 6, in <module>
    gym_env = GymEnv(env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gymenv.py", line 43, in __init__
    self.action_space = GymActionSpace(self.init_env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 131, in __init__
    self._fill_dict_act_space(dict_,
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 256, in _fill_dict_act_space
    my_type = SpaceType(low=low, high=high, shape=shape, dtype=dt)
  File "C:\Python38\lib\site-packages\gym\spaces\box.py", line 30, in __init__
    assert np.isscalar(low) and np.isscalar(high)
AssertionError
```

## Expected output

```
No errors
```

**Comment by BDonnot** [comment]
Hello,

Thanks for the detailed issue.

Unfortunately, i could not reproduce it on my computer, neither locally (on a windows 10 nor on a linux machine) nor on colab using one of the notebook in the google colab website, see for example https://colab.research.google.com/github/rte-france/Grid2Op/blob/master/getting_started/00_SmallExample.ipynb

Can you run this example:

```python
import sys
# to give extra info on the python version
print(sys.version)
# for extra info on the platform
print(sys.platform)

import grid2op
# extra info on grid2op
print(grid2op.__version__)

# to make sure you have the latest version of the environment
grid2op.update_env()

# now create it
env = grid2op.make("l2rpn_case14_sandbox")
# "make sure" it works
obs = env.reset()

# and uses the gym_compat module
from grid2op.gym_compat import GymEnv
gym_env = GymEnv(env)

# "make sure" it works
gym_obs = gym_env.reset()
print(gym_obs["a_ex"])
```

For me i get:

```
3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
win32
1.5.0
Environment "l2rpn_case14_sandbox" is up to date
Environment "rte_case14_realistic" is up to date
[ 155.4294    127.13095   102.94453   138.83089   108.19038    52.725002
  135.80658   434.52097   252.74222   649.2642     56.013855  183.57967
  324.4969     79.42569   319.6616    970.70337   312.82553   475.6461
 1045.0125    804.7695  ]
```

**Comment by BDonnot** [comment]
Hello,

Has this solved the issue ?

**Comment by vishrutmishra** [comment]
```3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
win32
1.5.0
Environment "l2rpn_case14_sandbox" is up to date
Environment "rte_case14_realistic" is up to date
Traceback (most recent call last):
  File "D:\projects\cse574\demo\grid2op-test.py", line 21, in <module>
    gym_env = GymEnv(env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gymenv.py", line 43, in __init__
    self.action_space = GymActionSpace(self.init_env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 131, in __init__
    self._fill_dict_act_space(dict_,
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 256, in _fill_dict_act_space
    my_type = SpaceType(low=low, high=high, shape=shape, dtype=dt)
  File "C:\Python38\lib\site-packages\gym\spaces\box.py", line 30, in __init__
    assert np.isscalar(low) and np.isscalar(high)
AssertionError```

This is the output of the script you gave @BDonnot

**Comment by BDonnot** [comment]
Can you upgrade to grid2op 1.5.1 and run this script again. 

It's hard to fix a bug I cannot reproduce :-/ And I really don't see what can cause that

**Comment by vishrutmishra** [comment]
I use pip install. no anaconda

when updating I get this message. 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
expertop4grid 0.0.1 requires Grid2Op==1.1.1, but you have grid2op 1.5.1.post1 which is incompatible.
expertop4grid 0.0.1 requires numpy==1.18.4, but you have numpy 1.20.2 which is incompatible.
expertop4grid 0.0.1 requires pandas==1.0.4, but you have pandas 1.2.3 which is incompatible.
Successfully installed grid2op-1.5.1.post1
```

the output of the script after is
```
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
win32
1.5.1.post1
Environment "l2rpn_case14_sandbox" is up to date
Environment "rte_case14_realistic" is up to date
Traceback (most recent call last):
  File "D:\projects\cse574\demo\grid2op-test.py", line 21, in <module>
    gym_env = GymEnv(env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gymenv.py", line 43, in __init__
    self.action_space = GymActionSpace(self.init_env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 131, in __init__
    self._fill_dict_act_space(dict_,
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 256, in _fill_dict_act_space
    my_type = SpaceType(low=low, high=high, shape=shape, dtype=dt)
  File "C:\Python38\lib\site-packages\gym\spaces\box.py", line 30, in __init__
    assert np.isscalar(low) and np.isscalar(high)
AssertionError
[Finished in 37.089s]
```

**Comment by BDonnot** [comment]
I just thought about something.

You try to delete the folder containing the environment, and try to download it again.

First, locate where it is:

```python
import grid2op
env = grid2op.make("l2rpn_case14_sandbox")
print(env.get_path_env())
```
Then delete the folder: above (for example "c:\Users\YourName\grid2op_datasets\l2rpn_case14_sandbox" )

And then download it again:
```python
import grid2op
env = grid2op.make("l2rpn_case14_sandbox")
```

Thanks

**Comment by vishrutmishra** [comment]
I did that and the output was:
```
C:\Python38\lib\site-packages\grid2op\MakeEnv\Make.py:329: UserWarning: It is the first time you use the environment "l2rpn_case14_sandbox".
We will attempt to download this environment from remote
  warnings.warn(_MAKE_FIRST_TIME_WARN.format(dataset_name))
downloading the training data, this may take a while.
Extract the tar archive in "C:\Users\username\data_grid2op"
You may now use the environment "l2rpn_case14_sandbox" with the available data by invoking:
	env = grid2op.make("l2rpn_case14_sandbox")
C:\Users\mvish\data_grid2op\l2rpn_case14_sandbox
Traceback (most recent call last):
  File "D:\projects\cse574\demo\grid2op-gym.py", line 8, in <module>
    gym_env = GymEnv(g2op_env)  # create the gym environment
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gymenv.py", line 43, in __init__
    self.action_space = GymActionSpace(self.init_env)
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 131, in __init__
    self._fill_dict_act_space(dict_,
  File "C:\Python38\lib\site-packages\grid2op\gym_compat\gym_act_space.py", line 256, in _fill_dict_act_space
    my_type = SpaceType(low=low, high=high, shape=shape, dtype=dt)
  File "C:\Python38\lib\site-packages\gym\spaces\box.py", line 30, in __init__
    assert np.isscalar(low) and np.isscalar(high)
AssertionError
[Finished in 112.845s]
```

The error is still there.

**Comment by BDonnot** [comment]
This is really weird...

Have you tried to upgrade openai gym and numpy ?

From a windows cmd:

```
py -m pip install -U numpy gym
```
That might cause an issue, but i don't know why you got a problem that i don't, on the same machine, with the same python version.

**Comment by vishrutmishra** [comment]
That fixed it.

```
Is gym_env and open AI gym environment: True
[Finished in 5.051s]
```

Thanks.

**Comment by vishrutmishra** [comment]
I think I downgraded gym coz one e of the approaches from last year said 'it needed gym 0.12' or something and then forgot to update it back.

**Comment by BDonnot** [comment]
Thanks for the feedback, 

I reopen the issue to remember to add the "gym minimal version" in the grid2Op package (so that other people don't run into this issue).

**Comment by BDonnot** [comment]
Added in latest version
