### ISSUE TITLE
Bug when loading environment with no shunt

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#199]
## Environment
 - Grid2op version: `1.5.1`
 - System: ` osx`
 - Additional system information

## Bug description

For this environment which has no shunts, a bug occurs at sh_p, sh_q, sh_v, sh_bus = env.backend.shunt_info() in grid2op/Observation/CompleteObservation.py
[l2rpn_2019_nohubs.zip](https://github.com/rte-france/Grid2Op/files/6390732/l2rpn_2019_nohubs.zip)

### Code snippet

```python
import grid2op

timestep = 1
env_folder = "l2rpn_2019_nohubs"
env = grid2op.make(env_folder)
env.fast_forward_chronics(nb_timestep= timestep)
obs = env.get_obs()

```

## Current output

```
Traceback (most recent call last):
  File "/Users/antoinemarot/dev/ExpertOp4Grid/Test_Grid2op_Shunt.py", line 7, in <module>
    obs = env.get_obs()
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/grid2op/Environment/BaseEnv.py", line 1336, in get_obs
    res = self._observation_space(env=self)
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/grid2op/Observation/ObservationSpace.py", line 184, in __call__
    res.update(env=env, with_forecast=self.with_forecast)
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/grid2op/Observation/CompleteObservation.py", line 186, in update
    sh_p, sh_q, sh_v, sh_bus = env.backend.shunt_info()
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/grid2op/Backend/PandaPowerBackend.py", line 1068, in shunt_info
    shunt_v = self._grid.res_bus["vm_pu"].loc[self._grid.shunt["bus"].values].values.astype(dt_float)
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/pandas/core/indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/pandas/core/indexing.py", line 1954, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/pandas/core/indexing.py", line 1595, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/Users/antoinemarot/dev/ExpertOp4Grid/venv_expert4grid/lib/python3.6/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [UInt64Index([8], dtype='uint64')] are in the [index]"

```

## Expected output

```
The expected output and/or expected behavior description
```

**Comment by BDonnot** [comment]
Hello,

The bug cannot be reproduced (no file are attached).

Grid2op works perfectly wtih environment without shunt:
```python
import grid2op
env = grid2op.make("rte_case5_example", test=True)
print(f"Number of shunt: {env.n_shunt}")
```

There is no shunt there and there are no problem either.

Possible issue:
- the grid file is corrupted
- the grid file is no longer supported by pandapower

To fix, you can try:
- use ligntsim2grid and see if it works
- upgrade your grid file
- reset the pandapower version to a known working version
- don't use a grid file not supported by grid2op


I am closing this issue as it does not appear to be a grid2op issue but rather a pandapower / wrong file one

**Comment by marota** [comment]
Look for "l2rpn_2019_nohubs.zip" for the file attached (it was hidden in the post I agree, my bad).
This is extracted from a test in ExpertOp4Grid that used to pass with Grid2OP 1.1.1 with pandapower 2.2.2
It fails with Grid2OP 1.5.1 with pandapower 2.2.2
But upgrading pandapower to 2.6.0 make it work. 

So given that, issue is solved (just need to remember that there might be a slight problem with pandapower 2.2.2 and Grid2OP 1.5.1)
