### ISSUE TITLE
Can't use a lambda function in set_filter when filtering before creating a multi-process env

### ISSUE THREAD

**Issue by EBoguslawski** [rte-france/Grid2Op#291]
## Environment
 - Grid2op version: `1.6.5`
 - System: `windows`
 - Python version: `3.8`

## Bug description

When I pre-filter chronics with the `.set_filter` method and a lambda function, I get an error if I convert it to a multi-process environment after. However, the code works well if I use a named function instead of a lambda function.

### Code

This code doesn't work on my machine :

```python
import grid2op
from grid2op.Environment import SingleEnvMultiProcess
import re

if __name__ == '__main__':
    env = grid2op.make(dataset='l2rpn_neurips_2020_track1_small')
    # ------- bug when filtering with a lambda function
    env.chronics_handler.real_data.set_filter(lambda x: re.match(".*00$", x) is not None)
    env.chronics_handler.real_data.reset()
    # -------

    # Convert to multi-process environment
    envs = SingleEnvMultiProcess(env=env, nb_env=2)
    envs.reset()
    envs.close()
```
But this code does work well:

```python
import grid2op
from grid2op.Environment import SingleEnvMultiProcess
import re

def filter_fun(x):
    return re.match(".*00$", x) is not None

if __name__ == '__main__':
    env = grid2op.make(dataset='l2rpn_neurips_2020_track1_small')
    # ------- works well when using a named function
    env.chronics_handler.real_data.set_filter(filter_fun)
    env.chronics_handler.real_data.reset()
    # -------

    # Convert to multi-process environment
    envs = SingleEnvMultiProcess(env=env, nb_env=2)
    envs.reset()
    envs.close()
```

### Returned error

When using a lambda function in set_filter, this error is returned:

```
Traceback (most recent call last):
  File "d:/Users/boguslawskieva/these/Expe_BinbinChen/agent_Binbinchen/SeniorStudent/bug_set_filter_multi_env.py", line 17, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    envs = SingleEnvMultiProcess(env=env, nb_env=2)
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\site-packages\grid2op\Environment\SingleEnvMultiProcess.py", line 78, in __init__  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\spawn.py", line 116, in spawn_main
    super().__init__(envs,
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\site-packages\grid2op\Environment\BaseMultiProcessEnv.py", line 296, in __init__ 
    exitcode = _main(fd, parent_sentinel)
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    p.start()
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Users\boguslawskieva\Miniconda3\envs\baselines\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x00000225432D5040>: attribute lookup <lambda> on __main__ failed
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'd:/Users/boguslawskieva/these/Expe_BinbinChen/agent_Binbinchen/SeniorStudent/bug_set_filter_multi_env.py']' command failed.  (See above for error)
```

**Comment by BDonnot** [comment]
Hi,

It appears to work on linux but not on windows. I suspect windows sucks to code in python, especially using multi processing :-(

There is unfortunately not much we can do for that (except what you already did: find a workaround), sorry :-(
