### ISSUE TITLE
RuntimeError: Impossible to read the statistics for attribute "grid_operational_cost_score"

### ISSUE THREAD

**Issue by liushaohuai5** [rte-france/Grid2Op#293]
## Environment
 - Grid2op version: `1.6.4 & 1.6.5`
 - System: `ubuntu18.04, ...`
 - Additional system information

## Bug description
<RuntimeError: Impossible to read the statistics for attribute "grid_operational_cost_score">

### Command line

```bash
python test_grid2op_score.py
```

### Code snippet

```python
import grid2op
from grid2op.utils import ScoreICAPS2021
from grid2op.Agent import DoNothingAgent

env = grid2op.make("l2rpn_icaps_2021_small")
agent = DoNothingAgent(env.action_space)
episodes = 0
nb_scenario = 4
print('\tI am testing agent')
l2rpn_critic = ScoreICAPS2021(env,
                              nb_scenario=nb_scenario,
                              env_seeds=[0 for _ in range(nb_scenario)],
                              agent_seeds=[0 for _ in range(nb_scenario)]
                             )
test_score, _, _ = l2rpn_critic.get(agent)
print('\tI have done agent test!')
print(test_score)
... # Some code 
```

## Current output

```
root@k8sdeploy-n183:~/LossZero# python test_grid2op_score.py
        I am testing agent
Traceback (most recent call last):
  File "test_grid2op_score.py", line 13, in <module>
    agent_seeds=[0 for _ in range(nb_scenario)]
  File "/usr/local/lib/python3.7/dist-packages/grid2op/utils/icaps_2021_scores.py", line 110, in __init__
    score_names=["grid_operational_cost_scores", "alarm_cost_scores"])
  File "/usr/local/lib/python3.7/dist-packages/grid2op/utils/l2rpn_2020_scores.py", line 135, in __init__
    score_names=score_names)
  File "/usr/local/lib/python3.7/dist-packages/grid2op/utils/l2rpn_2020_scores.py", line 151, in _init_stat
    scores, ids_ = stat.get(score_names[0])
  File "/usr/local/lib/python3.7/dist-packages/grid2op/utils/underlying_statistics.py", line 324, in get
    raise RuntimeError(f"Impossible to read the statistics for attribute \"{attribute_name}\"")
RuntimeError: Impossible to read the statistics for attribute "grid_operational_cost_scores"
```

## Expected output

```
I am testing agent
I have done agent test
**(score)
```

**Comment by BDonnot** [comment]
Hello,

This code snippet seems to be working on my computer. Have you upgraded grid2op recently ?

If so you might want to delete the previously saved statistics with:

```python
import grid2op
from grid2op.utils import EpisodeStatistics
env = grid2op.make(...)
EpisodeStatistics.clean_all_stats(env)
```

And restart your computation again.

Can you let me know if it solves your issue ?

**Comment by BDonnot** [comment]
I'm closing the issue then :-)
