### ISSUE TITLE
Environment object has no attribute '_is_test'

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#361]
## Environment
 - Grid2op version: `0.x.x`
 - System: `windows, osx, ubuntu16.04, ...`
 - Additional system information

## Bug description

AttributeError: 'Environment_l2rpn_case14_sandbox' object has no attribute '_is_test'

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
import grid2op
import unittest
import warnings

from grid2op.Runner import Runner

class Issue361Tester(unittest.TestCase):
    def setUp(self) -> None:
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore")
            self.env = grid2op.make("l2rpn_case14_sandbox", test=True)
    
    def tearDown(self) -> None:
        self.env.close()
        return super().tearDown()
    
    def test_copy(self):
        
        env_cpy = self.env.copy()
        assert hasattr(self.env.backend, "_my_kwargs")
        assert hasattr(env_cpy.backend, "_my_kwargs")
        env_cpy.close()
    
    def test_runner(self):
        env_cpy = self.env.copy()
        runner = Runner(**env_cpy.get_params_for_runner())
        res = runner.run(nb_episode=1, max_iter=10)
        # this crashed above
        env_cpy.close()
```

## Current output

```
======================================================================
ERROR: test_runner (__main__.Issue360Tester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_issue_glop_360.py", line 34, in test_runner
    runner = Runner(**env_cpy.get_params_for_runner())
  File "/home/donnotben/Documents/grid2op_dev/grid2op/Environment/Environment.py", line 1672, in get_params_for_runner
    res["_is_test"] = self._is_test  # TODO not implemented !!
AttributeError: 'Environment_l2rpn_case14_sandbox' object has no attribute '_is_test'
```

## Expected output

No error should be raised

**Comment by BDonnot** [comment]
F
