### ISSUE TITLE
PPO training does not work on grid2op==1.8.2.dev4

### ISSUE THREAD

**Issue by Didayolo** [rte-france/Grid2Op#450]
Training a PPO from stable-baselines3 works on `grid2op==1.8.1` but fails on `grid2op==1.8.2.dev4` with the following error message:
```python
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```

History of upgrades done on different images:

```
# image didayolo/l2rpn:2023
grid2op==1.8.1
```

```
# image didayolo/l2rpn:2023.1
stable_baselines3==1.8.0
gym==0.26.2
```

```
# image didayolo/l2rpn:2023.2
grid2op==1.8.2.dev4
```

In `didayolo/l2rpn:2023.2`, training a PPO fails:

```python
Traceback (most recent call last):
  File "/tmp/codalab/tmpG1bGOb/run/ingestion_program/ingestion.py", line 330, in <module>
    main()
  File "/tmp/codalab/tmpG1bGOb/run/ingestion_program/ingestion.py", line 268, in main
    submitted_agent.train()
  File "/tmp/codalab/tmpG1bGOb/run/program/submission/my_agent.py", line 14, in train
    return _train(self.env, iterations=3000, n_epochs=10, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/l2rpn_baselines/PPO_SB3/train.py", line 305, in train
    agent.nn_model.learn(total_timesteps=iterations,
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 308, in learn
    return super().learn(
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 239, in learn
    total_timesteps, callback = self._setup_learn(
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 412, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 75, in reset
    self._save_obs(env_idx, obs)
  File "/usr/local/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 105, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```

But it works in `didayolo/l2rpn:2023` and in `didayolo/l2rpn:2023.1`. Therefore, the bug comes from `grid2op==1.8.2.dev4`.

**Comment by BDonnot** [comment]
Can you follow the issue template? Thanks
