### ISSUE TITLE
grid2op.make use deprecated attribute iteritems of Pandas.Series

### ISSUE THREAD

**Issue by GoubetClem** [rte-france/Grid2Op#451]
## Environment
 - Grid2op version: `1.8.2`
 - System: `Ubuntu 22.04 LTS.`
 - VM

## Bug description
`grid2op.make` function to initiate environment use deprecated attribute of pandas.Series (>=2.0.*)

## How to reproduce
pip install pandas==2.0.1
python3
import grid2op
grid2op.make()

## Current output
Error and process ending
```
`Traceback (most recent call last):

  File "/home/goubetcle/Git_Projects/l2rpn_idf_2023/set_thermal_limit/generate_flows.py", line 132, in <module>

    env_ref = grid2op.make(args.env_name,

  File "/home/goubetcle/Git_Projects/Grid2Op/grid2op/MakeEnv/Make.py", line 430, in make

    return make_from_path_fn(

  File "/home/goubetcle/Git_Projects/Grid2Op/grid2op/MakeEnv/MakeFromPath.py", line 839, in make_from_dataset_path

    env = Environment(

  File "/home/goubetcle/Git_Projects/Grid2Op/grid2op/Environment/Environment.py", line 165, in __init__

    self._init_backend(

  File "/home/goubetcle/Git_Projects/Grid2Op/grid2op/Environment/Environment.py", line 235, in _init_backend

    self.backend.load_grid(

  File "/home/goubetcle/Git_Projects/l2rpn_idf_2023/.venv_l2rpn2023/lib/python3.10/site-packages/lightsim2grid/lightSimBackend.py", line 369, in load_grid

    self.init_pp_backend.load_grid(path, filename)

  File "/home/goubetcle/Git_Projects/Grid2Op/grid2op/Backend/PandaPowerBackend.py", line 557, in load_grid

    self._init_private_attrs()

  File "/home/goubetcle/Git_Projects/Grid2Op/grid2op/Backend/PandaPowerBackend.py", line 777, in _init_private_attrs

    self.__pp_backend_initial_grid = copy.deepcopy(

  File "/usr/lib/python3.10/copy.py", line 153, in deepcopy

    y = copier(memo)

  File "/home/goubetcle/Git_Projects/l2rpn_idf_2023/.venv_l2rpn2023/lib/python3.10/site-packages/pandapower/auxiliary.py", line 208, in __deepcopy__

    _preserve_dtypes(result[k], v.dtypes)

  File "/home/goubetcle/Git_Projects/l2rpn_idf_2023/.venv_l2rpn2023/lib/python3.10/site-packages/pandapower/auxiliary.py", line 268, in _preserve_dtypes

    for item, dtype in list(dtypes.iteritems()):

  File "/home/goubetcle/Git_Projects/l2rpn_idf_2023/.venv_l2rpn2023/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__

    return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'iteritems'

`
```
## Expected output
the initiated env

**Comment by GoubetClem** [comment]
easy call, sorry for the false alert-
