### ISSUE TITLE
Issue while installing Grid2op 0.5.8

### ISSUE THREAD

**Issue by mjothy** [rte-france/Grid2Op#50]
Note : The issue is not present with 0.5.7

I have the following error when running either pipenv install or pip install : 
```
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mjothy\AppData\Local\Temp\pip-install-jee8j02w\grid2op\setup.py", line 19, in <module>
        import numba
      File "c:\users\mjothy\.virtualenvs\chronix2grid-finrbh4i\lib\site-packages\numba\__init__.py", line 15, in <module>
        from . import config, errors, _runtests as runtests, types
      File "c:\users\mjothy\.virtualenvs\chronix2grid-finrbh4i\lib\site-packages\numba\config.py", line 18, in <module>
        import llvmlite.binding as ll
      File "c:\users\mjothy\.virtualenvs\chronix2grid-finrbh4i\lib\site-packages\llvmlite\binding\__init__.py", line 6, in <module>
        from .dylib import *
      File "c:\users\mjothy\.virtualenvs\chronix2grid-finrbh4i\lib\site-packages\llvmlite\binding\dylib.py", line 4, in <module>
        from . import ffi
      File "c:\users\mjothy\.virtualenvs\chronix2grid-finrbh4i\lib\site-packages\llvmlite\binding\ffi.py", line 154, in <module>
        raise OSError("Could not load shared object file: {}".format(_lib_name))
    OSError: Could not load shared object file: llvmlite.dll
```
https://github.com/numba/llvmlite/issues/498
This issue seems to indicate that "The wheels may have been built with the wrong ABI setting." I have no idea what it means, but the issue is clearly related to the numba link.

Maybe grid2op requires a specific version of numba ?

Thank you.

**Comment by BDonnot** [comment]
Hello Mario,

Yes i tried to have grid2op install numba when installing grid2op  to take into account issue #42 .
> Maybe grid2op requires a specific version of numba ?

During the install of grid2op, the installation script tried to do, from a subprocess: `python -m pip install -U numba` ("python" is called through "sys.executable")
It should install the latest numba version available.

Can you try to install this package without any "pipenv" but more simply in a virtual env ?
I tried on my own windows computer and could not reproduce the issue.

I will further look into this.

Benjamin

**Comment by BDonnot** [comment]
Hello Mario,

I tried to improve the installation script of grid2op for the next version (0.6.0). Can you try to install it from my development branch:
```bash
pip install git+https://github.com/BDonnot/Grid2Op.git@opponent
```

Can you try to install it and tell me if it's working ?

Thanks a lot

Benjamin

**Comment by BDonnot** [comment]
Hello @mjothy , can you check whether the new version fixed this issue ?

I didn't manage to reproduce your bug on none of my MS Windows machine, but I hope the few modifications i made to the installation script were enough to fix it.

Let me know if it did not.

Benjamin
