### ISSUE TITLE
Possibility of running full duration of chronics with FromMultiEpisodeData for agent comparison

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#537]
So when using the FromMultiEpisodeData the second agent can only run until the time step where the first agent terminated. For example if we use a RandomAgent and follow up with a DoNothingAgent using `FromMultiEpisodeData` class then the DoNothingAgent have the option to run until the time step where the RandomAgent terminated and not the full chronic. If we consider the example below, for the `Scenario_december_000` the Random agent ran 141 steps, for the same episode now mentioned as chronic 0, the DoNothing agent ran until 142 steps and not the whole 8064 steps. But this does not allow to understand how far can the DoNothing agent execute for. Is it anyway to accomplish this?

Random Agent
```
chronics at: Scenario_december_000      total score: 2224.979736        time steps: 141/8062
chronics at: Scenario_december_001      total score: 10176.507812       time steps: 728/8062
chronics at: Scenario_december_002      total score: 19384.091797       time steps: 1532/8062
chronics at: Scenario_december_003      total score: 13651.573242       time steps: 933/8062
chronics at: Scenario_december_004      total score: 14281.053711       time steps: 1078/8062
chronics at: Scenario_december_005      total score: 11349.540039       time steps: 803/8062
chronics at: Scenario_december_006      total score: 3640.885498        time steps: 253/8062
chronics at: Scenario_december_007      total score: 11827.672852       time steps: 828/8062
chronics at: Scenario_december_008      total score: 8884.326172        time steps: 533/8062
chronics at: Scenario_december_009      total score: 7009.403320        time steps: 455/8062
```

Do Nothing Agent
```
chronics at: 0  total score: 7986.913574        time steps: 141/142
chronics at: 1  total score: 31563.019531       time steps: 571/729
chronics at: 2  total score: 15257.829102       time steps: 281/1533
chronics at: 3  total score: 27409.562500       time steps: 451/934
chronics at: 4  total score: 39832.851562       time steps: 717/1079
chronics at: 5  total score: 42306.437500       time steps: 754/804
chronics at: 6  total score: 3813.688232        time steps: 65/254
chronics at: 7  total score: 39820.648438       time steps: 732/829
chronics at: 8  total score: 5145.033203        time steps: 77/534
chronics at: 9  total score: 12538.629883       time steps: 246/456
```

Sample script

```python
import grid2op
from grid2op.Runner import Runner
from grid2op.Agent import RecoPowerlineAgent, TopologyGreedy, RandomAgent
from lightsim2grid import LightSimBackend
from grid2op.Chronics import MultifolderWithCache
import re

# path_agent = ....
nb_episode = 10
env_name = "l2rpn_neurips_2020_track1_small"  # or any other name
env = grid2op.make(env_name,
                   backend=LightSimBackend(),
                   chronics_class=MultifolderWithCache)

env.chronics_handler.real_data.set_filter(lambda x: re.match(".*december.*", x) is not None)
env.chronics_handler.real_data.reset()

# optional (change the parameters to allow the )
param = env.parameters
param.NO_OVERFLOW_DISCONNECTION = True
env.change_parameters(param)
env.reset()
# end optional

runner = Runner(**env.get_params_for_runner(),
                #agentClass=RecoPowerlineAgent),
                agentClass=RandomAgent)
res = runner.run(nb_episode=nb_episode,
           path_save="./saved_multiepisode_agent_36bus/")

print("Random Agent")
for _, chron_name, cum_reward, nb_time_step, max_ts in res:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)

env.close()

from grid2op.Chronics import FromMultiEpisodeData
from grid2op.Opponent import FromEpisodeDataOpponent
from grid2op.Episode import EpisodeData

path_agent = "./saved_multiepisode_agent_36bus/"  # same as above
# env_name = "l2rpn_case14_sandbox" # same as above

# path_agent is the path where data coming from a grid2op runner are stored
# NB it should come from a do nothing agent, or at least
# an agent that does not modify the injections (no redispatching, curtailment, storage)
li_episode = EpisodeData.list_episode(path_agent)

env2 = grid2op.make(env_name,
                   chronics_class=FromMultiEpisodeData,
                   data_feeding_kwargs={"li_ep_data": li_episode},
                   opponent_class=FromEpisodeDataOpponent,
                   opponent_attack_cooldown=1,
              )
# li_ep_data in this case is a list of anything that is accepted by `FromOneEpisodeData`

obs = env2.reset()

runner_params = env2.get_params_for_runner()
runner = Runner(**runner_params)

res2 = runner.run(nb_episode=nb_episode,
                        nb_process=1
                        )
print("Do Nothing Agent")
for _, chron_name, cum_reward, nb_time_step, max_ts in res2:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)

env2.close()

```

**Comment by BDonnot** [comment]
I close this issue as you appear to have been satisfied with my previous answer. If that is not the case then feel free to re open it.

**Comment by AvisP** [comment]
Hi Benjamin,

Thanks for your response and suggestion, I got side tracked with other work and couldn't respond earlier. Yeah I will have to follow the process you suggested by running the full scenario with overload disconnection switched off. I was hoping that there is something that you already have for comparing different agents in the competitions you host on the same scenarios.

In this regard, I would like to ask if it is possible to look at specific interval for different chronics. For example I am trying to look at certain days for 288 time steps by specifying different staring time steps in the following code snippet but getting an error. Any help would be appreciated.

```python
import grid2op
from grid2op.Runner import Runner
from grid2op.Agent import RecoPowerlineAgent, TopologyGreedy, RandomAgent, DoNothingAgent
from lightsim2grid import LightSimBackend
from grid2op.Chronics import MultifolderWithCache
import re
from datetime import datetime, timedelta
# path_agent = ....
nb_episode = 5
env_name = "l2rpn_neurips_2020_track1_small"  # or any other name
env = grid2op.make(env_name,
                   backend=LightSimBackend(),
                   chronics_class=MultifolderWithCache)

env.chronics_handler.real_data.set_filter(lambda x: re.match(".*july.*", x) is not None)
env.chronics_handler.real_data.reset()

# optional (change the parameters to allow the )
param = env.parameters
param.NO_OVERFLOW_DISCONNECTION = True
env.change_parameters(param)
env.reset()
# end optional

runner = Runner(**env.get_params_for_runner(),
                #agentClass=RecoPowerlineAgent),
                # agentClass=RandomAgent
                )
res = runner.run(nb_episode=nb_episode,
           path_save="./saved_multiepisode_agent_36bus_DN/")

print("DoNtohing Agent")
for _, chron_name, cum_reward, nb_time_step, max_ts in res:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)

env.close()

# chronics at: Scenario_july_000  total score: 18138.451172       time steps: 198/8062
# chronics at: Scenario_july_001  total score: 18753.708984       time steps: 206/8062
# chronics at: Scenario_july_002  total score: 42719.980469       time steps: 502/8062
# chronics at: Scenario_july_003  total score: 73728.953125       time steps: 879/8062
# chronics at: Scenario_july_004  total score: 110531.515625      time steps: 1359/8062

from grid2op.Chronics import FromMultiEpisodeData
from grid2op.Opponent import FromEpisodeDataOpponent
from grid2op.Episode import EpisodeData

path_agent = "./saved_multiepisode_agent_36bus_DN/"  # same as above

li_episode = EpisodeData.list_episode(path_agent)

li_episode_subset = li_episode[:4]
start_datetime_list = [datetime(year=2019, month=1, day=1), datetime(year=2019, month=1, day=1), 
                       datetime(year=2019, month=1, day=2), datetime(year=2019, month=1, day=4)]
max_iter=288
time_interval_list = [timedelta(minutes=5), timedelta(minutes=5), timedelta(minutes=5), timedelta(minutes=5)]
env2 = grid2op.make(env_name,
                   chronics_class=FromMultiEpisodeData,
                   data_feeding_kwargs={"li_ep_data": li_episode_subset,
                                        "start_datetime":start_datetime_list,
                                        "time_interval":time_interval_list,
                                        "max_iter":288},
                   opponent_class=FromEpisodeDataOpponent,
                   opponent_attack_cooldown=1,
              )
# li_ep_data in this case is a list of anything that is accepted by `FromOneEpisodeData`
obs = env2.reset()

runner_params = env2.get_params_for_runner()
runner = Runner(**runner_params)

res2 = runner.run(nb_episode=nb_episode,
                        nb_process=1
                        )
print("Do Nothing Agent")
for _, chron_name, cum_reward, nb_time_step, max_ts in res2:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)

env2.close()
```
Error message
```
Traceback (most recent call last):
  File "/...../RLLIB_Practice4/multi_episode_36bus_DN_test.py", line 60, in <module>
    env2 = grid2op.make(env_name,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/...../venvs/L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/MakeEnv/Make.py", line 454, in make
    return make_from_path_fn(
           ^^^^^^^^^^^^^^^^^^
  File "/...../venvs/L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/MakeEnv/MakeFromPath.py", line 850, in make_from_dataset_path
    env = Environment(
          ^^^^^^^^^^^^
  File "/....../venvs/L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/Environment/environment.py", line 169, in __init__
    self._init_backend(
  File "/....../L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/Environment/environment.py", line 361, in _init_backend
    self.delta_time_seconds = dt_float(self.chronics_handler.time_interval.seconds)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'seconds'
```

**Comment by BDonnot** [comment]
Hello,

As usual, can you make a specific issue with minimal code to reproduce this bug?

This is probably a bug with the `FromMultiEpisodeData` and the Runner and is not directly related to the original issue.

As for the competitions, we run `Runner` with normal settings (specifying seeds and chronics ID) for all agents, save the results (with the runner) and then we use some tools such as Grid2Viz when we want to compare them "in depth". You can also use the EpisodeData for specific comparisons (this is what Grid2Viz used internally) 

For the leader boards score are computed (with appropriate classes, depending on the competition, see the `utils` module) and it's easier to compare agents score (single digit).

And finally, note that we always compare agents for episode of 1 week (approx 2017 or 2018 steps) in length. We don't cherry pick shorter "sub episodes": indeed this might caused issue with agent trained specifically on episode of 1w of duration but most importantly it might lead to dramatic impact on "time dependant" agents (including, but far from limited to, all the agent using "recurrent neural network")

**Comment by AvisP** [comment]
Thanks for your your prompt response. I will create a separate issue for it provide the code as minimal response.

I appreciate your word of caution and of course training on such shorter time frames will lead to improper behavior of agents so training is done over the full episode length. I have to validate trained agents on certain shorter "sub episodes" as to which agent is doing better under same conditions of environment which is why I am needing to do this.

And as a follow up, I was trying to used a LSTM network with rllib package but was having issues for Dsicrete Actions but not for Continuous actions. I will try to create a follow up on issue on that.
