### ISSUE TITLE
FromMultiEpisodeData issuing an error when trying to create an environment with specific interval for individual chronic

### ISSUE THREAD

**Issue by AvisP** [rte-france/Grid2Op#552]
I am trying to validate how separate trained agents perform on certain intervals for different chronics using the `FromMultiEpisodeData` class. For example I am trying to look at certain days for 288 time steps by specifying different staring time steps in the following code snippet but getting an error. Any help would be appreciated.

```python
import grid2op
from grid2op.Runner import Runner
from grid2op.Agent import RecoPowerlineAgent, TopologyGreedy, RandomAgent, DoNothingAgent
from lightsim2grid import LightSimBackend
from grid2op.Chronics import MultifolderWithCache
import re
from datetime import datetime, timedelta
# path_agent = ....
nb_episode = 5
env_name = "l2rpn_neurips_2020_track1_small"  # or any other name
env = grid2op.make(env_name,
                   backend=LightSimBackend(),
                   chronics_class=MultifolderWithCache)

env.chronics_handler.real_data.set_filter(lambda x: re.match(".*july.*", x) is not None)
env.chronics_handler.real_data.reset()

# optional (change the parameters to allow the )
param = env.parameters
param.NO_OVERFLOW_DISCONNECTION = True
env.change_parameters(param)
env.reset()
# end optional

runner = Runner(**env.get_params_for_runner(),
                #agentClass=RecoPowerlineAgent),
                # agentClass=RandomAgent
                )
res = runner.run(nb_episode=nb_episode,
           path_save="./saved_multiepisode_agent_36bus_DN/")

print("DoNtohing Agent")
for _, chron_name, cum_reward, nb_time_step, max_ts in res:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)

env.close()

# chronics at: Scenario_july_000  total score: 18138.451172       time steps: 198/8062
# chronics at: Scenario_july_001  total score: 18753.708984       time steps: 206/8062
# chronics at: Scenario_july_002  total score: 42719.980469       time steps: 502/8062
# chronics at: Scenario_july_003  total score: 73728.953125       time steps: 879/8062
# chronics at: Scenario_july_004  total score: 110531.515625      time steps: 1359/8062

from grid2op.Chronics import FromMultiEpisodeData
from grid2op.Opponent import FromEpisodeDataOpponent
from grid2op.Episode import EpisodeData

path_agent = "./saved_multiepisode_agent_36bus_DN/"  # same as above

li_episode = EpisodeData.list_episode(path_agent)

li_episode_subset = li_episode[:4]
start_datetime_list = [datetime(year=2019, month=1, day=1), datetime(year=2019, month=1, day=1), 
                       datetime(year=2019, month=1, day=2), datetime(year=2019, month=1, day=4)]
max_iter=288
time_interval_list = [timedelta(minutes=5), timedelta(minutes=5), timedelta(minutes=5), timedelta(minutes=5)]
env2 = grid2op.make(env_name,
                   chronics_class=FromMultiEpisodeData,
                   data_feeding_kwargs={"li_ep_data": li_episode_subset,
                                        "start_datetime":start_datetime_list,
                                        "time_interval":time_interval_list,
                                        "max_iter":288},
                   opponent_class=FromEpisodeDataOpponent,
                   opponent_attack_cooldown=1,
              )
# li_ep_data in this case is a list of anything that is accepted by `FromOneEpisodeData`
obs = env2.reset()

runner_params = env2.get_params_for_runner()
runner = Runner(**runner_params)

res2 = runner.run(nb_episode=nb_episode,
                        nb_process=1
                        )
print("Do Nothing Agent")
for _, chron_name, cum_reward, nb_time_step, max_ts in res2:
    msg_tmp = "chronics at: {}".format(chron_name)
    msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
    msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
    print(msg_tmp)

env2.close()
```
Error message
```
Traceback (most recent call last):
  File "/...../RLLIB_Practice4/multi_episode_36bus_DN_test.py", line 60, in <module>
    env2 = grid2op.make(env_name,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/...../venvs/L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/MakeEnv/Make.py", line 454, in make
    return make_from_path_fn(
           ^^^^^^^^^^^^^^^^^^
  File "/...../venvs/L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/MakeEnv/MakeFromPath.py", line 850, in make_from_dataset_path
    env = Environment(
          ^^^^^^^^^^^^
  File "/....../venvs/L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/Environment/environment.py", line 169, in __init__
    self._init_backend(
  File "/....../L2RPN_080_RLLIB_261_Grid2OP_195/lib/python3.11/site-packages/grid2op/Environment/environment.py", line 361, in _init_backend
    self.delta_time_seconds = dt_float(self.chronics_handler.time_interval.seconds)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'seconds'
```

**Comment by AvisP** [comment]
So to find a temporary solution to this issue but calling `FromOneEpisodeData` in a set of loops. I have a list of 4 episodes provided (here)[https://file.io/icpBR2hO9CbX]. I find that even when I providing a `start_datetime` and `chunk_size` in environment creation it has no effect and evaluates over the full episode rather than from starting time till the next 288 steps. I am providing the code and the output below in case there  is some mistake

```python
import grid2op
from grid2op.Runner import Runner
from grid2op.Agent import RecoPowerlineAgent, TopologyGreedy, RandomAgent, DoNothingAgent
from lightsim2grid import LightSimBackend
from grid2op.Chronics import MultifolderWithCache
import re
import numpy as np
from datetime import datetime, timedelta

path_agent = "./saved_multiepisode_agent_36bus_DN_4/"
nb_episode = 1
env_name = "l2rpn_neurips_2020_track1_small"  # or any other name

add_msg = "\n"

from grid2op.Chronics import FromMultiEpisodeData, FromOneEpisodeData
from grid2op.Opponent import FromEpisodeDataOpponent
from grid2op.Episode import EpisodeData

li_episode = EpisodeData.list_episode(path_agent)


for each_episode in li_episode[:3]:
    full_path, episode_studied = each_episode
    env2 = grid2op.make(env_name,
                        backend=LightSimBackend(),
                        chronics_class=FromOneEpisodeData,
                        data_feeding_kwargs={"ep_data": each_episode},
                        opponent_class=FromEpisodeDataOpponent,
                        opponent_attack_cooldown=1,
                        )

    runner_params = env2.get_params_for_runner()
    runner = Runner(**runner_params)

    res2 = runner.run(nb_episode=nb_episode,
                        # path_save="./saved_multiepisode_agent_36bus_DN_overload_trip/" 
                        )
    for _, chron_name, cum_reward, nb_time_step, max_ts in res2:
        msg_tmp = "\tchronics at: {}".format(episode_studied)#.format(chron_name)
        msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
        msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
        print(msg_tmp)

    add_msg += msg_tmp + "\n"
    env2.close()

    start_day = int(np.floor(nb_time_step/288))+1
    print(start_day)
    env3 = grid2op.make(env_name,
                        backend=LightSimBackend(),
                        chronics_class=FromOneEpisodeData,
                        data_feeding_kwargs={"ep_data": each_episode,
                                        "start_datetime": datetime(year=2019, month=7, day=start_day),
                                        "chunk_size": 288},
                        opponent_class=FromEpisodeDataOpponent,
                        opponent_attack_cooldown=1,
              )


    runner_params = env3.get_params_for_runner()
    runner = Runner(**runner_params)

    res3 = runner.run(nb_episode=nb_episode,
                        # path_save="./saved_multiepisode_agent_36bus_DN_overload_trip/"
                        )
    
    for _, chron_name, cum_reward, nb_time_step, max_ts in res3:
        msg_tmp = "\tchronics at: {}".format(episode_studied)#.format(chron_name)
        msg_tmp += "\ttotal score: {:.6f}".format(cum_reward)
        msg_tmp += "\ttime steps: {:.0f}/{:.0f}".format(nb_time_step, max_ts)
        print(msg_tmp)
    add_msg += msg_tmp + "\n"

    env3.close()

print(add_msg)
```

Output is

```
chronics at: Scenario_july_000  total score: 60126.390625       time steps: 730/8062 
chronics at: Scenario_july_000  total score: 60126.390625       time steps: 730/8062    
chronics at: Scenario_july_001  total score: 43438.457031       time steps: 509/8062    
chronics at: Scenario_july_001  total score: 43438.457031       time steps: 509/8062    
chronics at: Scenario_july_002  total score: 57504.988281  time steps: 684/8062    
chronics at: Scenario_july_002  total score: 57504.988281       time steps: 684/8062
```

As can be seen the res3 results are going over the whole of 8062 steps despite providing a start date and chunk size. Any swift resolution to tis would be appreciated. Thanks!

**Comment by BDonnot** [comment]
Please open a SEPARATE issue for all SEPARATE problem. I'm closing this one because I don't understand the link between first code and last one.

Also, the "start_datetime" is not doing what you think it does. It's just here to specify the date and time to put at the first observation. And the "chunk_size" definitely has no impact here. Please read the doc for its specific usage (completely unrelated to this type of time series by the way).
