### ISSUE TITLE
Making gif and matplotlib "canva"

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#77]
There is a problem when trying to make the gif of the episode (episode replay) due to a weird error in matplotlib:
```
Traceback (most recent call last):
  File "evaluate.py", line 104, in <module>
    evaluate(env,
  File "evaluate.py", line 86, in evaluate
    save_log_gif(logs_path, res)
  File "/home/benjamin/Documents/l2rpn-baselines/l2rpn_baselines/utils/save_log_gif.py", line 36, in save_log_gif
    ep_replay.replay_episode(episode_id=chron_name, gif_name=gif_name, display=False)
  File "/home/benjamin/Documents/grid2op_dev/grid2op/Episode/EpisodeReplay.py", line 110, in replay_episode
    frames.append(plot_runner.convert_figure_to_numpy_HWC(figure))
  File "/home/benjamin/Documents/grid2op_dev/grid2op/PlotGrid/PlotMatplot.py", line 156, in convert_figure_to_numpy_HWC
    figure.canvas.print_raw(buf)
  File "/home/benjamin/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 447, in print_raw
    FigureCanvasAgg.draw(self)
  File "/home/benjamin/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 390, in draw
    with RendererAgg.lock, \
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/benjamin/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2788, in _wait_cursor_for_draw_cm
    self.set_cursor(self._lastCursor)
  File "/home/benjamin/.local/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 468, in set_cursor
    self.canvas.get_property("window").set_cursor(cursord[cursor])
AttributeError: 'NoneType' object has no attribute 'set_cursor'
```

Probably the way to make gif should be set up differently.

**Comment by Tezirg** [comment]
Just logging some related google search result for later:
https://stackoverflow.com/questions/60964955/matplotlib-can-not-save-animation

**Comment by Tezirg** [comment]
Seems to work fine with `TkAgg`, but crashes with default `GTK3Agg` under Ubuntu20.

```python
import matplotlib
print(matplotlib.get_backend())
```

**Comment by BDonnot** [comment]
To force matplotlib using TkAgg you should:
1. install the necessary package, on my computer it was:
```
sudo apt-get install python3-tk
```
2. when want to use matplotlib, you wee to tell it to use "TkAgg": (from within a python script)
```python
import matplotlib
matplotlib.use("TkAgg")
# continue the rest of your script
```

**Comment by BDonnot** [comment]
**EDIT** 
You can visit this page to know how to configure matplotlib:
https://matplotlib.org/tutorials/introductory/customizing.html

What you need to do is to use the TkAgg backend. To modify matplotlib to use it permanently you need to :
1. install it (see previous comment)
2. locate the matplotlib configuration file. From within a python "shell":
```python
import matplotlib
matplotlib.matplotlib_fname()
```
This will get you something like `PATH/.local/lib/python3.8/site-packages/matplotlib/mpl-data/matplotlibrc` (for example)
3. modifiy this file (open your favorite text editor for example), find the place where the "matplotlib backend" is defined. On my machine it starts with:
```
## ***************************************************************************
## * BACKENDS                                                                *
## ***************************************************************************
## The default backend.  If you omit this parameter, the first working
## backend from the following list is used:
##     MacOSX Qt5Agg Qt4Agg Gtk3Agg TkAgg WxAgg Agg
## Other choices include:
##     Qt5Cairo Qt4Cairo GTK3Cairo TkCairo WxCairo Cairo Wx
##     PS PDF SVG Template
## You can also deploy your own backend outside of matplotlib by referring to
# backend : Agg
```
4. replace the last line by `backend : TkAgg` this gives you something like:
```
## ***************************************************************************
## * BACKENDS                                                                *
## ***************************************************************************
## The default backend.  If you omit this parameter, the first working
## backend from the following list is used:
##     MacOSX Qt5Agg Qt4Agg Gtk3Agg TkAgg WxAgg Agg
## Other choices include:
##     Qt5Cairo Qt4Cairo GTK3Cairo TkCairo WxCairo Cairo Wx
##     PS PDF SVG Template
## You can also deploy your own backend outside of matplotlib by referring to
backend : TkAgg
```
